version: '3.8'

services:
  db:
    image: public.ecr.aws/docker/library/postgres:15-alpine
    container_name: survey_new-db-1
    networks:
      - survey_net  # Same network name
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: 'NewSecurePass2026!'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  app:
    image: survey_app:latest
    container_name: survey_new-app-1
    ports:
      - "8091:8080"
    networks:
      - survey_net  # Same network name
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: 'NewSecurePass2026!'
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      db:
        condition: service_healthy
    restart: always

networks:
  survey_net:
    driver: bridge
