spring:
  jpa:
    hibernate:
      ddl-auto: update  # Automatically creates tables for you
    show-sql: true      # Shows the queries in your terminal (good for debugging)

logging:
  level:
    root: INFO
