name: Survey App CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout Code
        uses: actions/checkout@v4

      - name: 2. Set up Docker Buildx
        # This installs the engine that allows caching
        uses: docker/setup-buildx-action@v3

      - name: 3. Build Docker Image with Cache
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false # We aren't pushing to Docker Hub yet
          tags: survey-app:latest
          # THE MAGIC: This tells GitHub to save and find layers in its cache
          cache-from: type=gha
          cache-to: type=gha,mode=max
